document.addEventListener("DOMContentLoaded", () => {
  // Fetch the manifest generated by your GitHub Actions workflow
  fetch("docs/files.json")
    .then((response) => response.json()) // parse JSON manifest :contentReference[oaicite:6]{index=6}
    .then((files) => {
      const ul = document.getElementById("toc");
      files.forEach((file) => {
        // file.path is "docs/<name>.html"; link directly to that
        const li = document.createElement("li"); // create <li> :contentReference[oaicite:7]{index=7}
        const a = document.createElement("a"); // create <a> :contentReference[oaicite:8]{index=8}
        a.textContent = file.name; // display the filename
        a.href = file.path; // link to docs/<name>.html
        li.appendChild(a); // append <a> into <li> :contentReference[oaicite:9]{index=9}
        ul.appendChild(li); // append <li> into <ul> :contentReference[oaicite:10]{index=10}
      });
    })
    .catch((err) => console.error("Failed to load TOC:", err));
});
